import trackingTool from './lib/automatedUsageTrackingToolWrapper'

window.requestConsentQuestionButtonClickHandler = trackingTool.requestConsentQuestionButtonClickHandler
window.requestConsentConfirmationButtonClickHandler = trackingTool.requestConsentConfirmationButtonClickHandler
window.trackUsageButtonClickHandler = trackingTool.trackUsageButtonClickHandler
