# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish Package to npmjs

on:
  release:
    types: [published]

jobs:
  build:
    permissions:
      contents: read
      # id-token: write is required for the automatic generation of provenance statements
      id-token: write
    runs-on: ubuntu-latest
    # The GitHub Actions Environment containing the `NPM_TOKEN`secret
    environment: npmjs:@sap_oss/automated-usage-tracking-tool
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          # registry-url is required for releasing packages
          registry-url: "https://registry.npmjs.org"
      - run: npm ci

      - name: Publish package
        # --provenance enables the automatic generation of provenance statements
        # --access public is only hard required for the initial release, but it doesn't hurt having it setup
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
